### ISSUE TITLE
并不存在 MobileVLCKit.framework这个文件

### ISSUE THREAD

**Issue by Vanmm** [wuqiong/MobileVLCKit-SDK#6]
并不存在 MobileVLCKit.framework这个文件

**Comment by wuqiong** [comment]
那个框架的二进制资源由于单个文件大于100M。超出了github的限制。所以放在日本服务器上。需要你执行bootstrap脚本下载

**Comment by davidshiue** [comment]
jijiade-iMac:MobileVLCKit-SDK-master david$ ./bootstrap 
Downloading MobileVLCKit-framework-latest.tar.gz, wait...
error! MobileVLCKit-framework-latest.tar.gz doesn't exist!
